# SPDX-License-Identifier: MPL-2.0
#
# This file is part of Ramses Composer
# (see https://github.com/bmwcarit/ramses-composer-docs).
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - name: Create archive
      shell: bash
      run: |
        python3 .github/package.py ${{runner.workspace}}

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{runner.workspace}}/*.zip
